// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI requires a top-level `datasource` property for db commands.
    // Provide the connection URL and provider here for Prisma 7.
    url: env("DATABASE_URL"),
  },
});
